name: psikoHekim
services:
  psikopostgres:
    image: postgres:16
    container_name: psikohekim-psikopostgres-1
    environment:
      POSTGRES_USER: UserPsiko
      POSTGRES_PASSWORD: password
      POSTGRES_DB: psikohekim
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U UserPsiko -d psikohekim"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: psikohekim-redis-1
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports: ["6379:6379"]
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: psikohekim-elasticsearch-1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
    ports: ["9200:9200"]
    volumes: ["esdata:/usr/share/elasticsearch/data"]
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'" ]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  zeebe:
    image: camunda/zeebe:8.2.0
    container_name: psikohekim-zeebe-1
    environment:
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_CLASSNAME=io.camunda.zeebe.exporter.opensearch.OpensearchExporter
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_BULK_DELAY=5
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_INDEX_PREFIX=zeebe-record
    ports: 
      - "26500:26500"
      - "9600:9600"
    depends_on: [elasticsearch]
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: psikohekim-keycloak-1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
    ports: ["8080:8080"]
    restart: unless-stopped

volumes:
  pgdata:
  esdata:
