server:
  port: ${PORT:8083}

spring:
  config:
    import: "optional:configtree:/Users/fs648/Desktop/PsikoHekim/PsikoHekimBackend/secrets/"
  datasource:
    url: jdbc:postgresql://localhost:5433/psikohekim
    username: UserPsiko
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6380
      password: ${REDIS_PASSWORD:}

  security:
    oauth2:
      client:
        registration:
          google:
            # client-id / client-secret / redirect-uri YOK (secrets dolduracak)
            scope:
              - https://www.googleapis.com/auth/calendar.readonly
        provider:
          google:
            issuer-uri: https://accounts.google.com   # Ã¶nerilen
            # (authorization-uri/token-uri gerekmez)

zeebe:
  client:
    broker:
      gatewayAddress: localhost:26501
    security:
      plaintext: true

services:
  bpmn:
    url: http://localhost:8082

webhook:
  base-url: http://localhost:8083
  path: /webhooks/whatsapp

twilio:
  account:
    sid: ${twilio.account.sid}
  auth:
    token: ${twilio.auth.token}
  whatsapp:
    from: ${twilio.whatsapp.from}

microsoft:
  graph:
    client-id: ${microsoft.graph.client-id}
    client-secret: ${microsoft.graph.client-secret}
    tenant-id: ${microsoft.graph.tenant-id}
    redirect-uri: ${microsoft.graph.redirect-uri}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com_psikohekim.psikohekim_appt: DEBUG
    org.springframework.boot.context.config: DEBUG
